### ISSUE TITLE
keep getting this errors and it wont work 

### ISSUE THREAD

**Issue by zealsham** [robre/jsmon#3] opened 2020-08-26 00:42 UTC
i keep getting this erros affter i run jsmon
```
JSMon - Web File Monitor
Traceback (most recent call last):
  File "jsmon.py", line 144, in <module>
    main()        
  File "jsmon.py", line 132, in main
    ep_text = get_endpoint(ep)
  File "jsmon.py", line 42, in get_endpoint
    r = requests.get(endpoint)
  File "/home/zealsham/.local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/zealsham/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zealsham/.local/lib/python3.6/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/home/zealsham/.local/lib/python3.6/site-packages/requests/sessions.py", line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/zealsham/.local/lib/python3.6/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/home/zealsham/.local/lib/python3.6/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '# Ignore everything in this directory': No schema supplied. Perhaps you meant http://# Ignore everything in this directory?

```

**Comment by maverickNerd** [comment] 2020-08-30 08:57
Go to targets directory and delete .gitignore file, and then run jsmon.py, this error will not come then.

**Comment by zealsham** [comment] 2020-08-31 02:36
> Go to targets directory and delete .gitignore file, and then run jsmon.py, this error will not come then.

thank you very much maverickNerd.  it works , but i am curious to know why the .gitignore file is a problem

**Comment by maverickNerd** [comment] 2020-08-31 03:24
gitignore file has some content like this :" Ignore everything in this directory"

In jamon.py first function is get_endpoint_list, this function is going to targets dirrectory and making a list of content inside that folder. Since .gitignore has some content which does not has http:// before it, request.get() fails saying invalid url.

**Comment by yassineaboukir** [comment] 2020-10-14 14:07
The issue is fixed in the new version. I think this ticket can be closed now @robre :)

**Closed** 2020-10-14 19:51 UTC
